### ISSUE TITLE
run.py doesn't run

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Scanner_Python#16]
I am trying to realive this tool (the last time I made it wok was November 2019) around this commit
https://github.com/CityScope/CS_CityScoPy/commit/63680e791a57616b5c7037937213804561031974

I am now trying to rerun the tool with the current master but I unfortunattely get the following error 

`````
 CityScopy grid sent at: 2022-01-20 14:13:03.364056
Traceback (most recent call last):
  File "run.py", line 68, in <module>
    cityscopy.scan()
  File "/Users/arno/Projects/GitHub/CS_CityScoPy/cityscopy.py", line 107, in scan
    self.scanner_function(self.multiprocess_shared_dict)
  File "/Users/arno/Projects/GitHub/CS_CityScoPy/cityscopy.py", line 241, in scanner_function
    this_scanner_size = keystoned_video[y+scanner_reduction:y_red,
UnboundLocalError: local variable 'keystoned_video' referenced before assignment

 CityScopy grid sent at: 2022-01-20 14:13:03.986430
Process Process-2:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/arno/Projects/GitHub/CS_CityScoPy/cityscopy.py", line 403, in create_data_json
    scan_results = multiprocess_shared_dict['scan']
  File "<string>", line 2, in __getitem__
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
`````

**Comment by RELNO** [comment]
Could not replicate on my end, `run.py` works for me. there might be a case for updating your open-cv lib and try again 
`pip uninstall opencv-python`
`pip install opencv-python`

**Comment by agrignard** [comment]
Fix by this commit
https://github.com/CityScope/CS_CityScoPy/commit/da0b8f23abf97e8183f2c7cac54c0b432256598b
