### ISSUE TITLE
Black screen on scanner

### ISSUE THREAD

**Issue by SRobles97** [CityScope/CS_Scanner_Python#18]
I'm a student trying out the scanner on my laptop which has its own camera and I have an external webcam just in case. When I run the program from run.py the output looks like this
![imagen](https://user-images.githubusercontent.com/37591168/209997503-75d98f58-bb3b-44aa-a938-97e0d8657e00.png)

At first I thought the problem was opencv but I wrote a little program to just show the camera and it works
I haven't really tweaked anything in cityscopy.py or run.py, I just changed the 'camId' in the settings to -1

I meet the requirements to use the program
numpy==1.24.1
opencv_contrib_python==4.6.0.66
requests==2.25.1

I'm new at this so I don't know if I needed to change something before running the scanner or if I need to run other project from the CityScope to trying out the scanner

Any help or comment will be greatly appreciated

**Comment by RELNO** [comment]
Hi @SRobles97 thanks for your interest in the tool.
I've recently went back to maintain it, and am working on a major rewrite here https://github.com/CityScope/CS_CityScoPy/tree/cityio-types. It has hundreds of changes, most importantly it's matching https://cityscope.media.mit.edu/CS_cityscopeJS/ architecture for "scanning to web-app" pipeline. 

It would be great if you could clone that branch and take a look. The current master branch won't be relevant for much longer

**Comment by SRobles97** [comment]
Thank you for your answer, @RELNO 
I'm currently checking the branch and it has a lot of changes, I'm trying to setup the scanner on my laptop but the same problem presents.

The camera is in black and the scan shows the following on the web-app

![image](https://user-images.githubusercontent.com/37591168/210601772-f2e4df5b-f6c5-4979-91fa-a5f6c8c27b6f.png)

does the OS affects the scanner? I'm currently working on Windows 11 but I have a pc with Ubuntu on it

**Comment by RELNO** [comment]
@SRobles97 thanks for beta testing it! OS might affect the results since the camera drivers might not be well recognized by openCV. Can you paste here the terminal output?  
In the meantime, please take a look into the setting file https://github.com/CityScope/CS_CityScoPy/blob/cityio-types/cityscopy/settings/test.json and see if changing the `camId` attr. makes any difference

**Comment by SRobles97** [comment]
This is the terminal output
```bash
PS C:\Users\srova\PycharmProjects\CS_CityScoPy> python cityscopy.py --cityscopy setup --table_name test
"clear" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

        >>>>>> CityScoPY: A Scanner for MIT CityScope >>>>>>>>


                            |||||||||||
                            |||||||||||
                                    |||
                                    |||
                                    |||
                            |||      ||||||||||||
                            |||      ||||||||||||
                            |||               |||
                            |||               |||
                            |||               |||
                            ||||||||||||      |||
                            ||||||||||||      |||



        Copyright (C) {{ 2018 - 2023 }}  {{ Ariel Noyman }}

        Ariel Noyman
        https://github.com/CityScope/
        http://arielnoyman.com
        https://github.com/RELNO

        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        
Setting up a new CityScoPy instance for project: "test"...

- Getting field: "GEOGRID/properties/types/" from table: "test"

- Getting field: "GEOGRID/properties/header/" from table: "test"

- Getting field: "GEOGRIDDATA/" from table: "test"

- Settings saved to file at: 2023-01-04 14:15:42.709404

settings file log:
 {
    "CITYIO_API_URL": "https://cityio.media.mit.edu/api/table/",
    "CITYSCOPE_PRJ_NAME": "test",
    "TOGGLE_SEND_TO_CITYIO": true,
    "nrows": 50,
    "ncols": 100,
    "cell_gap": 10,
    "camId": 0,
    "interval": 2000,
    "gui": true,
    "mirror_cam": false,
    "keystone_points_list": "1451.0  347.0  1192.0  366.0  1811.0  1120.0  1152.0  1073.0",
    "types": {
        "Campus": {
            "name": "Campus",
            "color": [
                171,
                143,
                57
            ],
            "height": [
                0,
                15,
                30
            ],
            "cityscopy_id": 0,
            "cityscopy_pattern": "0000000000000000"
        },
        "Office": {
            "name": "Office",
            "color": [
                36,
                130,
                198
            ],
            "height": [
                0,
                50,
                100
            ],
            "cityscopy_id": 1,
            "cityscopy_pattern": "0000000000000001"
        },
        "Park": {
            "name": "Park",
            "color": [
                126,
                179,
                70
            ],
            "height": [
                0,
                0,
                0
            ],
            "cityscopy_id": 2,
            "cityscopy_pattern": "0000000000000010"
        },
        "Residential": {
            "name": "Residential",
            "color": [
                185,
                126,
                24
            ],
            "height": [
                0,
                50,
                100
            ],
            "cityscopy_id": 3,
            "cityscopy_pattern": "0000000000000011"
        }
    }
}
PS C:\Users\srova\PycharmProjects\CS_CityScoPy> python cityscopy.py --cityscopy scan --table_name test
"clear" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

        >>>>>> CityScoPY: A Scanner for MIT CityScope >>>>>>>>


                            |||||||||||
                            |||||||||||
                                    |||
                                    |||
                                    |||
                            |||      ||||||||||||
                            |||      ||||||||||||
                            |||               |||
                            |||               |||
                            |||               |||
                            ||||||||||||      |||
                            ||||||||||||      |||



        Copyright (C) {{ 2018 - 2023 }}  {{ Ariel Noyman }}

        Ariel Noyman
        https://github.com/CityScope/
        http://arielnoyman.com
        https://github.com/RELNO

        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

GEOGRIDDATA.json loaded to memory
CityScoPy grid sent at: 2023-01-04 14:16:05.959075 to cityIO endpoint { test }

CityScoPy grid sent at: 2023-01-04 14:16:14.973703 to cityIO endpoint { test }
****
```

when I change the camId this is the output

```bash
PS C:\Users\srova\PycharmProjects\CS_CityScoPy> python cityscopy.py --cityscopy setup --table_name test
"clear" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

        >>>>>> CityScoPY: A Scanner for MIT CityScope >>>>>>>>


                            |||||||||||
                            |||||||||||
                                    |||
                                    |||
                                    |||
                            |||      ||||||||||||
                            |||      ||||||||||||
                            |||               |||
                            |||               |||
                            |||               |||
                            ||||||||||||      |||
                            ||||||||||||      |||



        Copyright (C) {{ 2018 - 2023 }}  {{ Ariel Noyman }}

        Ariel Noyman
        https://github.com/CityScope/
        http://arielnoyman.com
        https://github.com/RELNO

        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        
Setting up a new CityScoPy instance for project: "test"...

- Getting field: "GEOGRID/properties/types/" from table: "test"

- Getting field: "GEOGRID/properties/header/" from table: "test"

- Getting field: "GEOGRIDDATA/" from table: "test"

- Settings saved to file at: 2023-01-04 14:19:13.540545

settings file log:
 {
    "CITYIO_API_URL": "https://cityio.media.mit.edu/api/table/",
    "CITYSCOPE_PRJ_NAME": "test",
    "TOGGLE_SEND_TO_CITYIO": true,
    "nrows": 50,
    "ncols": 100,
    "cell_gap": 10,
    "camId": -1,
    "interval": 2000,
    "gui": true,
    "mirror_cam": false,
    "keystone_points_list": "1451.0  347.0  1192.0  366.0  1811.0  1120.0  1152.0  1073.0",
    "types": {
        "Campus": {
            "name": "Campus",
            "color": [
                171,
                143,
                57
            ],
            "height": [
                0,
                15,
                30
            ],
            "cityscopy_id": 0,
            "cityscopy_pattern": "0000000000000000"
        },
        "Office": {
            "name": "Office",
            "color": [
                36,
                130,
                198
            ],
            "height": [
                0,
                50,
                100
            ],
            "cityscopy_id": 1,
            "cityscopy_pattern": "0000000000000001"
        },
        "Park": {
            "name": "Park",
            "color": [
                126,
                179,
                70
            ],
            "height": [
                0,
                0,
                0
            ],
            "cityscopy_id": 2,
            "cityscopy_pattern": "0000000000000010"
        },
        "Residential": {
            "name": "Residential",
            "color": [
                185,
                126,
                24
            ],
            "height": [
                0,
                50,
                100
            ],
            "cityscopy_id": 3,
            "cityscopy_pattern": "0000000000000011"
        }
    }
}
PS C:\Users\srova\PycharmProjects\CS_CityScoPy> python cityscopy.py --cityscopy scan --table_name test 
"clear" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

        >>>>>> CityScoPY: A Scanner for MIT CityScope >>>>>>>>


                            |||||||||||
                            |||||||||||
                                    |||
                                    |||
                                    |||
                            |||      ||||||||||||
                            |||      ||||||||||||
                            |||               |||
                            |||               |||
                            |||               |||
                            ||||||||||||      |||
                            ||||||||||||      |||



        Copyright (C) {{ 2018 - 2023 }}  {{ Ariel Noyman }}

        Ariel Noyman
        https://github.com/CityScope/
        http://arielnoyman.com
        https://github.com/RELNO

        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

GEOGRIDDATA.json loaded to memory
Traceback (most recent call last):
  File "C:\Users\srova\PycharmProjects\CS_CityScoPy\cityscopy.py", line 90, in <module>   
    main()
  File "C:\Users\srova\PycharmProjects\CS_CityScoPy\cityscopy.py", line 39, in main       
    scanner.scan()
  File "C:\Users\srova\PycharmProjects\CS_CityScoPy\cityscopy\Scanner\Scanner.py", line 66, in scan
    self.scanner_function(self.multiprocess_shared_dict)
  File "C:\Users\srova\PycharmProjects\CS_CityScoPy\cityscopy\Scanner\Scanner.py", line 188, in scanner_function
    this_scanner_size = keystoned_video[y+scanner_reduction:y_red,
UnboundLocalError: local variable 'keystoned_video' referenced before assignment
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\srova\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\srova\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\srova\PycharmProjects\CS_CityScoPy\cityscopy\helpers.py", line 74, in create_data_json
    scan_results = multiprocess_shared_dict['scan']
  File "<string>", line 2, in __getitem__
  File "C:\Users\srova\AppData\Local\Programs\Python\Python310\lib\multiprocessing\managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "C:\Users\srova\AppData\Local\Programs\Python\Python310\lib\multiprocessing\connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\srova\AppData\Local\Programs\Python\Python310\lib\multiprocessing\connection.py", line 285, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] Se está cerrando la canalización
PS C:\Users\srova\PycharmProjects\CS_CityScoPy> 
```

**Comment by RELNO** [comment]
Looks like the first `camId` is the right one (no cam error as we can see in the second try). This leads me to believe there might be a dipper openCV <-> linux/windows issue. I wonder if you can test this minimal openCV camera capture script and see what you get https://www.geeksforgeeks.org/python-opencv-capture-video-from-camera/

**Comment by SRobles97** [comment]
I'll try the script. By the way, this is the terminal output on Ubuntu
```bash
 >>>>>> CityScoPY: A Scanner for MIT CityScope >>>>>>>>


                            |||||||||||
                            |||||||||||
                                    |||
                                    |||
                                    |||
                            |||      ||||||||||||
                            |||      ||||||||||||
                            |||               |||
                            |||               |||
                            |||               |||
                            ||||||||||||      |||
                            ||||||||||||      |||



        Copyright (C) {{ 2018 - 2023 }}  {{ Ariel Noyman }}

        Ariel Noyman
        https://github.com/CityScope/
        http://arielnoyman.com
        https://github.com/RELNO

        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        
GEOGRIDDATA.json loaded to memory
[ WARN:0@0.214] global /io/opencv/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/sebastian/.local/lib/python3.10/site-packages/cv2/qt/plugins"
Traceback (most recent call last):
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy.py", line 90, in <module>
    main()
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy.py", line 39, in main
    scanner.scan()
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy/Scanner/Scanner.py", line 66, in scan
    self.scanner_function(self.multiprocess_shared_dict)
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy/Scanner/Scanner.py", line 188, in scanner_function
    this_scanner_size = keystoned_video[y+scanner_reduction:y_red,
UnboundLocalError: local variable 'keystoned_video' referenced before assignment
CityScoPy grid sent at: 2023-01-04 14:28:07.451635 to cityIO endpoint { test }

Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy/helpers.py", line 74, in create_data_json
    scan_results = multiprocess_shared_dict['scan']
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

and this is the output with camId = -1

```bash
 >>>>>> CityScoPY: A Scanner for MIT CityScope >>>>>>>>


                            |||||||||||
                            |||||||||||
                                    |||
                                    |||
                                    |||
                            |||      ||||||||||||
                            |||      ||||||||||||
                            |||               |||
                            |||               |||
                            |||               |||
                            ||||||||||||      |||
                            ||||||||||||      |||



        Copyright (C) {{ 2018 - 2023 }}  {{ Ariel Noyman }}

        Ariel Noyman
        https://github.com/CityScope/
        http://arielnoyman.com
        https://github.com/RELNO

        >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        
GEOGRIDDATA.json loaded to memory
[ WARN:0@0.214] global /io/opencv/modules/videoio/src/cap_v4l.cpp (902) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/sebastian/.local/lib/python3.10/site-packages/cv2/qt/plugins"
Traceback (most recent call last):
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy.py", line 90, in <module>
    main()
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy.py", line 39, in main
    scanner.scan()
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy/Scanner/Scanner.py", line 66, in scan
    self.scanner_function(self.multiprocess_shared_dict)
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy/Scanner/Scanner.py", line 188, in scanner_function
    this_scanner_size = keystoned_video[y+scanner_reduction:y_red,
UnboundLocalError: local variable 'keystoned_video' referenced before assignment
CityScoPy grid sent at: 2023-01-04 14:28:07.451635 to cityIO endpoint { test }

Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sebastian/cityscope/CS_CityScoPy/cityscopy/helpers.py", line 74, in create_data_json
    scan_results = multiprocess_shared_dict['scan']
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by RELNO** [comment]
camId is always a positive integer (0-8), so i'd try 0-3 or so to see if any of your IO/usb devices gets a signal. Are you running ubuntu inside windows or as a standalone?

**Comment by SRobles97** [comment]
I tested the script on both OS and it works showing the video capture of both devices
I'm running ubuntu as a standalone in a intel nuc minipc
the output on ubuntu shows the following
```bash
sebastian@sebastian-cityscope:~/cityscope$ /bin/python3 /home/sebastian/cityscope/script.py
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/sebastian/.local/lib/python3.10/site-packages/cv2/qt/plugins"
```

**Comment by RELNO** [comment]
[did not tried that myself but] can you try `sudo apt install qtwayland5` ? https://stackoverflow.com/questions/69994530/qt-qpa-plugin-could-not-find-the-qt-platform-plugin-wayland

**Comment by SRobles97** [comment]
I've installed qtwayland5 but it still shows the same output

**Comment by RELNO** [comment]
Only other thing I can think of is that your openCV version might not match - can you create a dedicated venv just for this repo?

**Comment by SRobles97** [comment]
I'm a beginner in python, what do I need to create a dedicate venv for the project?

**Comment by RELNO** [comment]
virtual environment, basically an encapsulated clean version of python with all the dependencies for a specific project, so that dep. won't overlap/break things. Follow this: https://docs.python.org/3/library/venv.html

**Comment by SRobles97** [comment]
is there a way to know all the exact dependencies a project need?

**Comment by RELNO** [comment]
requirement.txt will be added before I merge to master. For now, openCV and numpy are probably all you need to install. If anything else is missing, python should let you know

**Comment by SRobles97** [comment]
So I've tried a previous version of cityscopy that a classmate had and it turns out that the it shows the camera (being on my laptop it shows my face but I think it would work with legos) I used the same python interpreter as above

**Comment by RELNO** [comment]
to clarify - the version on the master branch do work for you and the new branch is not? or is it on a different machine/setup?

**Comment by SRobles97** [comment]
the current master branch and cityio-types branch for some reason don't work on both my windows laptop and ubuntu minipc but this version from years ago that I uploaded to show you https://github.com/SRobles97/Scanner-CityScoPy

**Comment by RELNO** [comment]
I set up the app on my linux machine and it works well. Your issue was that the initial keystone (the matrix of values you see in the right side in the `settings.json` file) was set to a different webcam. If you overwrite it with basic values (see the screenshot) you should start seeing the camera. Keep in mind that the tool cannot know what camera you use, so these values would have to adapt to what whatever setup you have. For that we have the Keystone app, but it is not yet ready in the new branch. 
So for now, give the settings file some baseline values, and then play with the keyboard keys to get the keystone you need.

![Screenshot from 2023-01-05 10-03-30](https://user-images.githubusercontent.com/14296774/210812056-9cd001a4-cb3a-487e-b1b7-e15b08d71778.png)

**Comment by SRobles97** [comment]
Thank you, I'm seeing the camera now.
![image](https://user-images.githubusercontent.com/37591168/210823361-e0a22471-6caa-47a5-a79f-5c97a1c2e10d.png)

How do I use the keystone app?
And how do I know what keystones I need?, I press the keyboard but it just let me select the corners and I don't have that info with the rgb values and coordinates that appears in your screenshot

**Comment by RELNO** [comment]
Keystone is your way to match the camera to the grid of Lego bricks (or other stuff you want to scan). When you already have the Lego grid ready, you can use the keyboard 1234 keys to select corners and wasd to move the selected corner and + or - to change how many pixels move each time. When you're done press q to save locally the keystone

**Comment by SRobles97** [comment]
how do I change the side of the grids?
